# Generated by Django 5.0.1 on 2024-02-03 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accommodation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accreditation_number', models.CharField(max_length=255)),
                ('number_of_beds', models.IntegerField()),
                ('email', models.EmailField(max_length=255)),
                ('cell_number', models.CharField(max_length=20)),
                ('street_address', models.CharField(max_length=255)),
                ('nearest_campus', models.CharField(max_length=255)),
                ('residence_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Accommodations',
            },
        ),
    ]
