# Generated by Django 5.0.1 on 2024-05-25 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accommodations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='accommodation',
            table='Accommodation',
        ),
    ]
